# Change these first
owner: legtvar # Your GitHub organization or username, where this repository lives
repo: kafe-status # The name of this repository

sites:
  - name: Kafe
    url: http://kafe.fi.muni.cz/
  - name: Kafe - API
    url: https://kafe.fi.muni.cz/swagger/index.html
  - name: Garrigue Games
    url: https://games.muni.cz
  - name: Garrigue Games - API
    url: https://games.muni.cz/api/v1/games

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /kafe-status
  logoUrl: https://kafe.fi.muni.cz/favicon.svg
  name: Kafe
  introTitle: "Status of the **Kafe** website and related services."
  introMessage: This is a status page which shows **real-time** status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


assignees:
  - cafour
  - roseckyj

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
